[project]
name = "nanogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.5.3",
    "numpy>=2.3.2",
    "omegaconf>=2.3.0",
    "pathlib>=1.0.1",
    "torch>=2.8.0",
]
